git:
  quiet: true
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
after_success:
  - codecov -f coverage/*.json
script:
  - npm install codecov -g
  - npm run test:coverage
  - npm run build:dev